# -*- coding: utf-8 -*-
"""0306讀取csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbxpiYtIKnscXCVKxbkKboN9aQJ4o_31
"""

# 列出檔案
system("ls", TRUE)

# 列出檔案
system("ls", TRUE)

#載入reader 套件
library(readr)

#讀取.csv檔案
dataset <- read.csv("20210305動物資料.csv")

#印出dataset
dataset

#預覽前10筆
head(dataset$A_Name_Ch, n=10)

#預覽後10筆
tail(dataset$A_Name_Ch, n=10)

#搜尋 企鵝
dataset[grepl("企鵝",dataset$A_Name_Ch),]

#搜尋 蛙
dataset[grepl("蛙",dataset$A_Name_Ch),]

#計算 門
table(dataset$A_Phylum)

#計算 綱
table(dataset$A_Class)

#計算 目
table(dataset$A_Order)

#計算 科
table(dataset$A_Family)

# 保育等級
table(dataset$A_Conservation)